name: Shell Commands

on: [push]

env:
  BRANCH_NAMEX: ${{ github.ref_name }}
jobs:
    unete-shell-commands:
      environment: ${{ env.BRANCH_NAMEX }}
      runs-on: ubuntu-latest
      steps:
        - name : echo a string
          run: echo "Hello World"
        - name : multiline command
          run: |
            echo "Hello"
            echo "World"

